{
 "title": "Docker Containers Watch 📦",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Cumulative system CPU time consumed by Containers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_system_seconds_total{name=~\"vaued_app_container|cadvisor|grafana_container|redis|prometheus_container\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"running\"}"
    },
    {
     "expr": "engine_daemon_container_states_containers{state=\"paused\"}"
    },
    {
     "expr": "engine_daemon_container_states_containers{state=\"stopped\"}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "The count of containers in various states",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers"
    }
   ]
  },
  {
   "title": "Swarm status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "swarm_manager_tasks_total" }
   ]
  },
  {
   "title": "Failed image builds Information ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(builder_builds_failed_total[$__rate_interval])"
    }
   ]
  }
 ]
}