{
 "title": "Docker Performance Watch 🐋",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Docker Engine Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{job=\"docker\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Docker CPU Usage Overtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"docker\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Docker CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"docker\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Docker RAM Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_memory_bytes{job=\"docker\"}/(1024*1024*1024)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Docker Architecture",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{job=\"docker\"}",
     "legendFormat": "{{architecture}}"
    }
   ]
  },
  {
   "title": "Docker Container Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=~\"paused|running|stopped\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Docker Container Actions Average Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(engine_daemon_container_actions_seconds_count{action=~\"create|delete|start|stop\",job=\"docker\"}[1m])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Docker Image Actions Average Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(engine_daemon_image_actions_seconds_count{}[1m])",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}