{
 "title": "Flask Endpoints Watch 📈",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Main Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WebApp Version⚙️",
   "type": "stat",
   "description": "Version of the Flask WebApp running in the docker container ",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_version_info{}", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "WebApp Config 👩🏽‍💻",
   "type": "stat",
   "description": "Version of the Flask WebApp running in the docker container ",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_version_info{}", "legendFormat": "{{config}}" }
   ]
  },
  {
   "title": "Request Latency /s  🤖",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(app_request_latency_seconds_count{endpoint=~\"/|/MovieAPI|/admin_dashboard|/auth|/sign_out\"}[1m])/rate(app_request_latency_seconds_sum{endpoint=~\"/|/MovieAPI|/admin_dashboard|/auth|/sign_out\"}[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Total Requests Count 🔃",
   "type": "stat",
   "description": "GET/POST Request Counts per Main Endpoint of the flask webapp",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (app_request_count_total{endpoint=~\"/|/MovieAPI|/admin_dashboard|/auth|/sign_out\", http_status=~\"2..|3..|4..|5..\"})",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Successful Requests ✅",
   "type": "stat",
   "description": "GET/POST Request Counts per Main Endpoint of the flask webapp",
   "gridPos": { "h": 13, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint, http_status) (app_request_count_total{endpoint=~\"/|/MovieAPI|/admin_dashboard|/auth|/sign_out|/dev\", http_status=\"200\"})",
     "legendFormat": "{{endpoint}} [{{http_status}}]"
    }
   ]
  },
  {
   "title": "Failed Requests /Endpoint ❌",
   "type": "stat",
   "description": "Failed GET/POST Request Counts per Main Endpoint of the flask webapp",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint, http_status) (app_request_count_total{endpoint=~\"/|/MovieAPI|/admin_dashboard|/auth|/sign_out|/dev\", http_status!=\"200\"})",
     "legendFormat": "{{endpoint}} [{{http_status}}]"
    }
   ]
  },
  {
   "title": "Total Failed Requests Overtime ❌⌚",
   "type": "timeseries",
   "description": "Failed GET/POST Request Counts per Main Endpoint of the flask webapp",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count by (http_status) (app_request_count_total{http_status!=\"200\"})",
     "legendFormat": "{{http_status}}"
    }
   ]
  }
 ]
}