{
 "title": "Python Performance Watch",
 "description": "Keeps an eye on the Docker Engine Performance Metrics",
 "tags": [ "Docker" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Python Process Start Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"vaued_app_container:9091\"}*1000"
    }
   ]
  },
  {
   "title": "Physical RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"vaued_app_container:9091\"}/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "Virtual RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"vaued_app_container:9091\"}/(1024*1024*1024)"
    }
   ]
  },
  {
   "title": "Python Implementation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_info{implementation=\"CPython\",version=\"3.9.12\"}",
     "legendFormat": "{{implementation}}"
    }
   ]
  },
  {
   "title": "Python Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_info{implementation=\"CPython\",version=\"3.9.12\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Objects Collected by Python Garbage Collector",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total{}[4m])",
     "legendFormat": "Generation: {{generation}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"vaued_app_container:9091\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"vaued_app_container:9091\"}/process_max_fds{instance=\"vaued_app_container:9091\"}"
    }
   ]
  },
  {
   "title": "Max File Descriptors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_max_fds{instance=\"vaued_app_container:9091\"})"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"vaued_app_container:9091\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}