global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vaued-flask-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['vaued_app_container:9091']

  - job_name: 'docker'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:9323' ]